# @package _global_

# order in which configs override each other (/* - denotes a relative search path)
defaults:
  - /base_gs
  - override /strategy: mcmc
  - _self_

model:
  default_density: 0.5
  default_scale_factor: 0.1

loss:
  use_opacity: true
  lambda_opacity: 0.01

  use_scale: true
  lambda_scale: 0.01

checkpoint:
  iterations: ${int_list:[ 7000, 30000 ]}

# Bilateral grid parameters
bilateral_grid:
  enabled: false
  lr: 0.002
  grid_X: 16
  grid_Y: 16
  grid_W: 8
